config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :contact_mailer, only: [:new, :create] do
    collection do
      get :confirmation
    end
  end

  get '/conditions' => 'static_pages#conditions'
  get '/home' => 'static_pages#home'
  get '/map' => 'static_pages#map'

  resources :reports, except: [:edit] do
    resources :comments, only: [:create, :update, :destroy]
    resources :report_likes, only: [:create, :destroy]
  end

  resources :replies

  resources :users, only: [:show, :edit, :update, :destroy]

  root to: "static_pages#home"

  namespace :admin do
    root to: 'admin#index'
    resources :users, :reports
  end
end

app/models/user.rb
class User < ApplicationRecord
  after_create :send_welcome

  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable
  has_many :reports
  has_many :comments
  has_many :replies
  has_many :report_likes
  validates :nickname, presence: true

  attr_accessor :login

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    login = conditions.delete(:login)
    if login
      where(conditions.to_h).where("lower(email) = :value OR lower(nickname) = :value", { value: login.downcase }).first
    elsif conditions.key?(:email) || conditions.key?(:nickname)
      where(conditions.to_h).first
    end
  end

  private

  def send_welcome
    UserMailer.welcome(self).deliver_now
  end

  def send_password_change_notification
    UserMailer.password_changed(self).deliver_now
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :check_if_admin

  def index
    @users = User.all
  end

  def destroy
    @user = User.find(params['id'])
    if !User.find_by(nickname: ENV['DELETE_USER_NICKNAME'], email: ENV['DELETE_USER_EMAIL'])
      @delete_user = User.create(nickname: ENV['DELETE_USER_NICKNAME'], email: ENV['DELETE_USER_EMAIL'], password: ENV['DELETE_USER_PASSWORD'], password_confirmation: ENV['DELETE_USER_PASSWORD'])
    else
      @delete_user = User.find_by(nickname: ENV['DELETE_USER_NICKNAME'], email: ENV['DELETE_USER_EMAIL'])
    end
    if @user.reports.count == 0
      @user.destroy
      flash[:alert] = "Le compte a bien été supprimé !"
      redirect_to admin_users_path
    else
      @user.reports.each do |report|
        report.update(user_id: @delete_user.id)
      end
      @user.destroy
      flash[:alert] = "Le compte a bien été supprimé !"
      redirect_to admin_users_path
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user
  before_action :authenticate_current_user

  def edit
    @user = User.find(params[:id])
  end

  def update
    if @user.update(user_params, context: :user_update)
      redirect_to @user, notice: 'Profil mis à jour avec succès!'
    else
      render :edit
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def destroy
    @user = User.find(params['id'])
    if !User.find_by(nickname: ENV['DELETE_USER_NICKNAME'], email: ENV['DELETE_USER_EMAIL'])
      @delete_user = User.create(nickname: ENV['DELETE_USER_NICKNAME'], email: ENV['DELETE_USER_EMAIL'], password: ENV['DELETE_USER_PASSWORD'], password_confirmation: ENV['DELETE_USER_PASSWORD'])
    else
      @delete_user = User.find_by(nickname: ENV['DELETE_USER_NICKNAME'], email: ENV['DELETE_USER_EMAIL'])
    end
    if @user.reports.count == 0
      @user.destroy
      flash[:alert] = "Le compte a bien été supprimé !"
      redirect_to admin_users_path
    else
      @user.reports.each do |report|
        report.update(user_id: @delete_user.id)
      end
      @user.destroy
      flash[:alert] = "Le compte a bien été supprimé !"
      redirect_to admin_users_path
    end
  end

  private

  def authenticate_user
    unless current_user
      flash[:alert] = "Merci de vous connecter pour voir votre profil."
      redirect_to new_user_session_path
    end
  end

  def authenticate_current_user
    unless current_user == User.find(params['id'])
      flash[:alert] = "Vous ne pouvez accéder qu'à votre profil."
      redirect_to root_path
    end
  end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/_users.html.erb
<h5 class="text-center md:text-3xl py-4 cstm-dark">Liste des utilisateurs</h5>
<table class="w-full text-sm text-left cstm-dark mb-28 shadow-xl">
  <thead class="text-xs uppercase cstm-bg-dark text-center">
    <tr>
      <th scope="col" class="md:px-6 py-3 cstm-yellow">
        Pseudo
      </th>
      <th scope="col" class="md:px-6 py-3 cstm-yellow">
        Email
      </th>
      <th scope="col" class="md:px-6 py-3 cstm-yellow">
        Suppression
      </th>
    </tr>
  </thead>
  <% @users.each do |user| %>
    <% if (user.nickname != ENV['DELETE_USER_NICKNAME'] && user.email != ENV['DELETE_USER_EMAIL']) %>
      <tbody class="cstm-bg-sand text-center">
        <th scope="col" class="md:px-6 py-3">
          <%= user.nickname %>
        </th>
        <th scope="col" class="md:px-6 py-3">
          <%= user.email %>
        </th>
        <th scope="col" class="md:px-6 py-3">
          <% if !user.is_admin %>
            <%= button_to "Supprimer", admin_user_path(user), class:'cstm-bg-danger cstm-light font-bold py-2 md:px-4 rounded', form: { data: { turbo_confirm: "Es-tu sur de vouloir supprimer cet utilisateur ?" } }, method: :delete %>
          <% else %>
            <%= button_to "Supprimer", "", class:'cursor-not-allowed cstm-bg-dark cstm-light font-bold py-2 md:px-4 rounded' %>
          <% end %>
        </th>
      </tbody>
    <% end %>
  <% end %>
</table>

app/views/admin/users/index.html.erb
<article id="index">
  <section class="text-center pb-4">
    <%= button_to admin_root_path, class: "relative inline-flex items-center justify-center w-1/2 2xl:w-2/5 xl:w-2/5 md:w-2/5 lg:w-2/5 sm:w-2/5 h-12 overflow-hidden font-medium cstm-yellow transition duration-300 ease-out border-2 border-white rounded-lg shadow-md group", method: :get do %>
      <span class="cstm-bg-dark cstm-yellow absolute flex items-center justify-center w-full h-full transition-all duration-300 transform group-hover:translate-x-full ease">
        Revenir sur le dashboard admin
      </span>
      <span class="cstm-bg-primary absolute inset-0 flex items-center justify-center w-full h-full text-white duration-300 translate-x-full cstm-bg-primary group-hover:translate-x-0 ease">
        <svg class="w-6 h-6 transform -rotate-270" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 19l-7-7m0 0l7-7m-7 7h18"></path>
        </svg>
      </span>
    <% end %>
  </section>
  <section id="users" class="relative overflow-x-auto mx-auto">
    <%= render 'users', users: @users %>
  </section>
  <section class="lg:fixed items-center lg:top-[75%] lg:left-[78%]">
    <a href="#top" class="p-1.5 relative overflow-x-auto panel-anchor font-medium border-2 border-white rounded-lg shadow-md w-52 whitespace-nowrap">
      Revenir en haut de page
    </a>
  </section>
</article>