config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :contact_mailer, only: [:new, :create] do
    collection do
      get :confirmation
    end
  end

  get '/conditions' => 'static_pages#conditions'
  get '/home' => 'static_pages#home'
  get '/map' => 'static_pages#map'

  resources :reports, except: [:edit] do
    resources :comments, only: [:create, :update, :destroy]
    resources :report_likes, only: [:create, :destroy]
  end

  resources :replies

  resources :users, only: [:show, :edit, :update, :destroy]

  root to: "static_pages#home"

  namespace :admin do
    root to: 'admin#index'
    resources :users, :reports
  end
end

app/views/admin/admin/index.html.erb
<article class="grid grid-cols-1 gap-6 text-center">
  <h1 class="font-bold text-4xl pb-3">Dashboard admin</h1>
  <h2 class="font-bold text-3xl pb-3">Gestion des utilisateurs</h2>
  <% if @delete_user != nil %>
    <p> Il y a actuellement <%= @users.count - 1 %> personnes d'inscrites sur le site. </p>
  <% else %>
    <p> Il y a actuellement <%= @users.count %> personnes d'inscrites sur le site. </p>
  <% end %>
  <%= button_to admin_users_path, class: "relative inline-flex items-center justify-center p-28 px-28 py-8 overflow-hidden font-medium text-white transition duration-300 ease-out border-2 border-white rounded-full shadow-md group", method: :get do %>
    <span class="absolute inset-0 flex items-center justify-center w-full h-full text-white duration-300 -translate-x-full cstm-bg-yellow group-hover:translate-x-0 ease">
      <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width ="2" d="M14 5l7 7m0 0l-7 7m7-7H3"></path>
      </svg>
    </span>
    <span class="cstm-bg-sand absolute flex items-center justify-center w-full h-full cstm-dark transition-all duration-300 transform group-hover:translate-x-full ease">Accéder au panneau de gestion des utilisateurs</span>
  <% end %>
  <h2 class="font-bold text-3xl pb-3">Gestion des signalements</h2>
  <p> il y a actuellement <%= @reports.count %> signalements à valider. </p>
  <%= button_to admin_reports_path, class: "relative inline-flex items-center justify-center p-28 px-28 py-8 overflow-hidden font-medium text-white transition duration-300 ease-out border-2 border-white rounded-full shadow-md group", method: :get do %>
    <span class="absolute inset-0 flex items-center justify-center w-full h-full text-white duration-300 -translate-x-full cstm-bg-yellow group-hover:translate-x-0 ease">
      <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M14 5l7 7m0 0l-7 7m7-7H3"></path>
      </svg>
    </span>
    <span class="cstm-bg-sand absolute flex items-center justify-center w-full h-full cstm-dark transition-all duration-300 transform group-hover:translate-x-full ease">Accéder au panneau de gestion des signalements</span>
  <% end %>
</article>