config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :contact_mailer, only: [:new, :create] do
    collection do
      get :confirmation
    end
  end

  get '/conditions' => 'static_pages#conditions'
  get '/home' => 'static_pages#home'
  get '/map' => 'static_pages#map'

  resources :reports, except: [:edit] do
    resources :comments, only: [:create, :update, :destroy]
    resources :report_likes, only: [:create, :destroy]
  end

  resources :replies

  resources :users, only: [:show, :edit, :update, :destroy]

  root to: "static_pages#home"

  namespace :admin do
    root to: 'admin#index'
    resources :users, :reports
  end
end

app/models/report.rb
class Report < ApplicationRecord
  after_create :send_confirmation_email
  belongs_to :user
  enum :status, ["en cours de validation", "validé", "accepté","en cours","résolu"]

  validates :address, presence: true
  validates :content, presence: true, length: { minimum: 20, maximum: 550 }
  validates :title, presence: true, length: { minimum: 15, maximum: 60 }

  has_many_attached :images, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :replies, through: :comments
  has_many :report_likes, dependent: :destroy

  def send_confirmation_email
    ReportMailer.report_confirmation(self.user).deliver_now
    ReportMailer.admin_report_notification(self.user).deliver_now
  end

end

app/controllers/admin/reports_controller.rb
class Admin::ReportsController < ApplicationController
  before_action :check_if_admin

  def index
    @reports = Report.where(is_validate: nil)
    @validated = Report.where(status: 1)
    @accepted = Report.where(status: 2)
    @in_progress = Report.where(status: 3)
    @resolved = Report.where(status: 4)
  end

  def show
    @report = Report.find(params[:id])
  end

  def update
    @report = Report.find(params[:id])
    if params['report'] == "true"
      @report.update!(is_validate: true, status: 1)
      flash[:notice] = "Le signalement a été validé !"
      redirect_to admin_reports_path
    elsif params['report'] == "false"
      @report.update!(is_validate:false)
      flash[:notice] = "Le signalement a été refusé !"
      redirect_to admin_reports_path
    elsif params['report'] == "accepted"
      @report.update!(status: 2)
      flash[:notice] = "Le signalement a été accepté !"
      redirect_to admin_reports_path
    elsif params['report'] == "in progress"
      @report.update!(status: 3)
      flash[:notice] = "Les travaux sont en cours !"
      redirect_to admin_reports_path
    else params['report'] == "resolved"
      @report.update!(status: 4)
      flash[:notice] = "Les travaux sont terminés !"
      redirect_to admin_reports_path
    end
  end

  def destroy
    @report = Report.find(params['id'])
    @report.destroy
    flash[:notice] = "Le signalement a bien été supprimé !"
    redirect_to admin_reports_path
  end

end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :set_report, only: %i[ show edit update destroy ]
  before_action :authenticate_user, only: [:new, :create]
  before_action :check_if_admin_or_creator, only: [:show]

  def index
    @reports = Report.where(is_validate:true)
  end

  def show
  end

  def new
    @report = Report.new
  end

  def create
    @report = Report.new(report_params)
    coords = geocode_address(@report.address)
    @report.latitude = coords[:latitude]
    @report.longitude = coords[:longitude]
    respond_to do |format|
      if @report.images.attached? && @report.save
        format.html { redirect_to report_url(@report), notice: "Le signalement a correctement été créé." }
        format.json { render :show, status: :created, location: @report }
      elsif @report&.images.count == 0
        flash[:alert] = "Vous devez charger au moins une photo pour valider le signalement."
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      else
        flash[:alert] = "Erreur de saisie."
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @report.update(report_params)
        format.html { redirect_to report_url(@report), notice: "Le signalement a correctement été mise à jour." }
        format.json { render :show, status: :ok, location: @report }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @report.comments.each(&destroy)
    @report.destroy
    respond_to do |format|
      format.html { redirect_to reports_url, notice: "Le signalement a correctement été supprimé." }
      format.json { head :no_content }
    end
  end

  private

  def geocode_address(address)
    response = HTTParty.get("https://api-adresse.data.gouv.fr/search/?q=#{CGI::escape(address)}&limit=1")
    if response.code == 200
      coordinates = response.parsed_response["features"][0]["geometry"]["coordinates"]
      return { longitude: coordinates[0], latitude: coordinates[1] }
    else
      return { longitude: nil, latitude: nil }
    end
  end

  def set_report
    @report = Report.find(params[:id])
  end

  def report_params
    params.require(:report).permit(:title, :content, :is_validate, :user_id, :status_id, :address, :latitude, :longitude, images: [])
  end

end

app/helpers/admin/reports_helper.rb
module Admin::ReportsHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/_form.html.erb
<h1 class="pt-4 text-2xl text-center font-medium cstm-dark">
  Nouveau signalement
</h1>
<%= form_with(model: report, class: "contents") do |form| %>
  <section class="my-5">
    <%= form.label "Titre de votre signalement (entre 15 et 60 caractères) :", class: "block mb-2 text-sm font-bold cstm-dark" %>
    <%= form.text_field :title, class: "w-full px-3 py-2 text-sm leading-tight cstm-dark border-orange-300 rounded shadow appearance-none focus:border-orange-500 focus:ring-0 focus:shadow-outline" %>
  </section>
  <section class="my-5">
    <%= form.label "Décrivez la problématique rencontrée (entre 20 et 550 caractères) :", class: "block mb-2 text-sm font-bold cstm-dark" %>
    <%= form.text_area :content, rows: 4, class: "w-full px-3 py-2 text-sm leading-tight cstm-dark border-orange-300 rounded shadow appearance-none focus:border-orange-500 focus:ring-0 focus:shadow-outline" %>
  </section>
  <%= form.hidden_field :user_id, value: current_user.id %>
  <section class="my-5 relative", data-controller="api">
    <%= form.label "Adresse concernée par votre signalement (champ obligatoire) :", class: "block mb-2 text-sm font-bold cstm-dark"%>
    <%= form.text_field :address, id: "addressInput", placeholder: "Saisissez votre adresse", class: "w-full px-3 py-2 text-sm leading-tight cstm-dark border-orange-300 rounded shadow appearance-none focus:border-orange-500 focus:ring-0 focus:shadow-outline" %>
    <section id="resultContainer" class="absolute left-0 w-full bg-white rounded-b shadow-md border border-gray-200 z-10" style="display: none;">
      <ul id="addressResults" class="cursor-pointer"></ul>
    </section>
  </section>
  <section class="my-2 pt-2">
    <%= render 'reports/image_form', form: form %>
  </section>
  <section class = "flex justify-between pt-4">
    <%= link_to reports_path, class: "relative inline-flex items-center justify-center w-1/2 2xl:w-2/5 xl:w-2/5 md:w-2/5 lg:w-2/5 sm:w-2/5 h-12 overflow-hidden font-medium text-white transition duration-300 ease-out border-2 border-white rounded-lg shadow-md group", method: :get do %>
      <span class="cstm-bg-dark text-white absolute flex items-center justify-center w-full h-full cstm-dark transition-all duration-300 transform group-hover:translate-x-full ease">
        Retour à l'accueil
      </span>
      <span class="cstm-bg-primary absolute inset-0 flex items-center justify-center w-full h-full text-white duration-300 translate-x-full cstm-bg-yellow group-hover:translate-x-0 ease">
        <svg class="w-6 h-6 transform -rotate-270" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 19l-7-7m0 0l7-7m-7 7h18"></path>
        </svg>
      </span>
    <% end %>
    <%= button_to reports_path, class: "relative inline-flex items-center justify-center w-1/2 2xl:w-2/5 xl:w-2/5 md:w-2/5 lg:w-2/5 sm:w-2/5 h-12 overflow-hidden font-medium text-white transition duration-300 ease-out border-2 border-white rounded-lg shadow-md group", data: {turbo: false}, method: :post do %>
      <span class="absolute inset-0 flex items-center justify-center w-full h-full text-white duration-300 -translate-x-full cstm-bg-yellow group-hover:translate-x-0 ease bg-green-300">
        <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M14 5l7 7m0 0l-7 7m7-7H3"></path>
        </svg>
      </span>
      <span class="bg-amber-300 shadow-2xl cstm-bg-sand absolute flex items-center justify-center w-full h-full text-white transition-all duration-300 transform group-hover:translate-x-full ease">
        Créer mon signalement
      </span>
    <% end %>
  </section>
<% end %>

app/views/reports/_image_form.html.erb
<div class="dropzone dropzone-default dz-clickable flex justify-center w-full h-42 px-4 transition bg-white border-2 border-orange-300 border-dashed rounded-md appearance-none cursor-pointer hover:border-orange-400 focus:outline-none" data-controller="dropzone" data-dropzone-max-file-size="2" data-dropzone-accepted-files="image/*" data-dropzone-max-files="3" data-upload-multiple="true">
  <%= form.file_field :images, multiple: true, direct_upload: true, data: { dropzone_target: 'input' } %>
  <label>
    <span class="flex items-center space-x-2">
      <svg xmlns="http://www.w3.org/2000/svg" class="w-6 h-6 cstm-primary" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
        <path stroke-linecap="round" stroke-linejoin="round" d="M7 16a4 4 0 01-.88-7.903A5 5 0 1115.9 6L16 6a5 5 0 011 9.9M15 13l-3-3m0 0l-3 3m3-3v12"/>
      </svg>
      <div class="dropzone-msg dz-message needsclick cstm-dark font-medium">
        <h3 class="dropzone-msg-title">
          Glissez-déposez ou cliquez pour sélectionner vos images.
        </h3>
        <span class="dropzone-msg-desc">
          Vous devez sélectionner de une à trois images (taille maximum de 2Mo chacune).
        </span>
      </div>
    </span>
  </label>
</div>

app/views/reports/_report.html.erb
<div class="w-full lg:w-4/5 lg:ml-[10%] max-h-full lg:flex rounded-t mt-6">
  <% if report.images.any? %>
    <div class="h-48 lg:h-auto lg:w-96 flex-none bg-cover lg:rounded-l text-center overflow-hidden" style="background-image: url('<%= url_for(report.images.first) %>')" title="Image description"></div>
  <% end %>
  <div class="shadow-2xl border-r border-b border-l border-orange-400 lg:border-l-0 lg:border-t lg:border-orange-400 cstm-bg-primary rounded-b lg:rounded-b-none lg:rounded-r p-4 flex flex-col justify-between leading-normal flex-grow">
    <section class="mb-8">
      <p class="text-sm cstm-dark flex justify-end items-center">
        <% if report.status == "en cours de validation" %>
          <span class="flex justify-end ml-auto rounded-full px-3 py-2 text-sm font-semibold mr-2 cstm-new">
            <%= report.status %>
          </span>
        <% elsif report.status == "validé" %>
          <span class="flex justify-end ml-auto rounded-full px-3 py-2 text-sm font-semibold mr-2 cstm-validated">
            <%= report.status %>
          </span>
        <% elsif report.status == "accepté" %>
          <span class="flex justify-end ml-auto rounded-full px-3 py-2 text-sm font-semibold mr-2 cstm-accepted">
            <%= report.status %>
          </span>
        <% elsif report.status == "en cours" %>
          <span class="flex justify-end ml-auto rounded-full px-3 py-2 text-sm font-semibold mr-2 cstm-in-progress">
            <%= report.status %>
          </span>
        <% else %>
          <span class="flex justify-end ml-auto rounded-full px-3 py-2 text-sm font-semibold mr-2 cstm-resolved">
            <%= report.status %>
          </span>
        <% end %>
      </p>
      <div class="text-white font-bold text-4xl mb-4 mt-3">
        <%= report.title %>
      </div>
      <hr>
      <div class="text-white font-bold text-lg flex flex-start mr-auto mt-2">
        - <%= report.address %>
      </div>
      <p class="text-white text-base text-left pt-6 mb-4">
        <%= report.content %>
      </p>
      <hr>
    </section>
    <section class="flex justify-between items-center pb-6">
      <p class="text-white leading-none text-sm">
        par
        <% if report.user == nil %>
          utilisateur supprimé
        <% else %>
          <%= report.user.nickname %>
        <% end %>
        , le <%= report.created_at.strftime("%d/%m/%Y") %>
      </p>
    </section>
    <section class="flex justify-between items-center text-white">
      <figure>
        <i class="fa-solid fa-thumbs-up pr-1"></i>
        <%= report.report_likes.count %>
        <i class="fa-solid fa-comment-dots pl-4 pr-1"></i>
        <%= report.comments.count %>
      </figure> 
      <div class="flex justify-end items-center">
        <%= button_to report_path(report), class: "relative inline-flex items-center justify-center p-8 px-10 py-4 overflow-hidden font-medium text-white transition duration-300 ease-out border-2 border-white rounded-full shadow-md group", method: :get, data: { turbo: "false" } do %>
          <span class="absolute inset-0 flex items-center justify-center w-full h-full text-orange-400 duration-300 -translate-x-full bg-white group-hover:translate-x-0 ease">
            <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M14 5l7 7m0 0l-7 7m7-7H3"></path>
            </svg>
          </span>
          <span class="absolute flex items-center justify-center w-full h-full text-white transition-all duration-300 transform group-hover:translate-x-full ease">
            Détails
          </span>
        <% end %>
      </div>
    </section>  
  </div>
</div>

app/views/reports/_show.html.erb
<div class="max-w-screen-xl w-full grid grid-cols-1">
  <article class="shadow-2xl max-w-full max-h-full lg:flex rounded cstm-bg-primary">
    <div class="max-w-full max-h-full mx-auto px-4 sm:px-6 lg:px-8 mt-6">
      <div class="flex flex-col md:flex-row -mx-4">
        <section class="md:flex-1 px-4 ml-4 mt-4 mr-4">
          <div x-data="{ image: 1 }" x-cloak>
            <div class="h-64 md:h-80 rounded mb-4">
              <div x-show="image === 1" class="h-full w-full md:h-80 rounded mb-4">
                <a href="<%= url_for(@report.images[0]) %>" data-lightbox="report-images">
                  <%= image_tag(url_for(@report.images[0]), class: "rounded h-full w-full object-cover", alt: "Photo signalement n°1") %>
                </a>
              </div>
              <div x-show="image === 2" class="h-full w-full md:h-80 rounded mb-4">
                <a href="<%= url_for(@report.images[1]) %>" data-lightbox="report-images">
                  <%= image_tag(url_for(@report.images[1]), class: "rounded h-full w-full object-cover", alt: "Photo signalement n°2") %>
                </a>
              </div>
              <div x-show="image === 3" class="h-full w-full md:h-80 rounded mb-4">
                <a href="<%= url_for(@report.images[2]) %>" data-lightbox="report-images">
                  <%= image_tag(url_for(@report.images[2]), class: "rounded h-full w-full object-cover", alt: "Photo signalement n°3") %>
                </a>
              </div>
            </div>
            <div class="flex -mx-2 mb-4">
              <% @report.images.each_with_index do |image, index| %>
                <div class="flex-1 px-2">
                  <button x-on:click="image = <%= index + 1 %>" :class="{ 'ring-2 ring-indigo-300 ring-inset': image === <%= index + 1 %> }" class="focus:outline-none w-full rounded h-24 md:h-32">
                    <%= image_tag(image, class: 'h-full w-full rounded object-cover', alt: 'Miniature de l"image') %>
                  </button>
                </div>
              <% end %>
            </div>
          </div>
        </section>
        <section class="md:flex-1 px-4 pt-1">
          <p class="text-sm text-grey-dark flex justify-end items-center">
            <% if @report.status == "en cours de validation" %>
              <span class="flex justify-end ml-auto rounded-full px-3 py-2 text-sm font-semibold mr-2 cstm-new">
                <%= @report.status %>
              </span>
            <% elsif @report.status == "validé" %>
              <span class="flex justify-end ml-auto rounded-full px-3 py-2 text-sm font-semibold mr-2 cstm-validated">
                <%= @report.status %>
              </span>
            <% elsif @report.status == "accepté" %>
              <span class="flex justify-end ml-auto rounded-full px-3 py-2 text-sm font-semibold mr-2 cstm-accepted">
                <%= @report.status %>
              </span>
            <% elsif @report.status == "en cours" %>
              <span class="flex justify-end ml-auto rounded-full px-3 py-2 text-sm font-semibold mr-2 cstm-in-progress">
                <%= @report.status %>
              </span>
            <% else %>
              <span class="flex justify-end ml-auto rounded-full px-3 py-2 text-sm font-semibold mr-2 cstm-resolved">
                <%= @report.status %>
              </span>
            <% end %>
          </p>
          <h2 class="mb-2 mt-4 leading-tight tracking-tight font-bold text-white text-2xl md:text-3xl">
            <%= @report.title %>
          </h2>
          <hr>
          <div class="text-white font-bold text-lg flex flex-start mr-auto mt-2">
            - <%= @report.address %>
          </div>
          <p class="text-white mt-4 pb-4">
            <%= @report.content %>
          </p>
          <hr>
          <p class="text-white text-sm mb-2 flex justify-start pt-4 pb-4">
            par
            <% if @report.user == nil %>
              utilisateur supprimé          
            <% else %>
              <%= @report.user.nickname %>
            <% end %>
            , le <%= @report.created_at.strftime("%d/%m/%Y") %>
          </p>
          <section class="flex justify-between items-center pt-18 text-white">
            <%= turbo_frame_tag "jaime" do %>
              <figure class="flex align-baseline items-center">
                <% if already_exist?(@report) == false %>
                  <% if current_user %>
                    <%= @report.report_likes.count %>
                    <div class="border-2 border-white px-1 ml-1 rounded">
                      <%= button_to report_report_likes_path(@report.id), data: { turbo_frame: "jaime" }, remote: true, method: :post, class:"flex justify-between items-center" do %>
                        <i class="fa-solid fa-thumbs-up pr-1"></i>
                        <p class="pr-1">
                          J'aime
                        </p>
                      <% end %>
                    </div>
                  <% else %>
                    <%= @report.report_likes.count %>
                    <div class="border-2 border-white px-1 ml-1 rounded">
                      <%= button_to new_user_session_path, remote: true, method: :get, class:"flex justify-between items-center", data: {turbo:false} do %>
                        <i class="fa-solid fa-thumbs-up pr-1"></i>
                        <p class="pr-1">
                          J'aime
                        </p>
                      <% end %>
                    </div>
                  <% end %>
                <% else %>
                  <%= @report.report_likes.count %>
                  <div class="border-2 border-white px-1 ml-1 rounded">
                    <%= button_to report_report_like_path(report_id: @report.id, id: current_user.id), data: { turbo_frame: "jaime" }, method: :delete, class:"flex justify-between items-center" do %>
                      <i class="fa-solid fa-thumbs-up fa-rotate-180 pl-1"></i>
                      <p class="pr-1">
                        Je n'aime plus
                      </p>
                    <% end %>
                  </div>
                <% end %>
                <i class="fa-solid fa-comment-dots pl-6 pr-1"></i>
                <%= @report.comments.count %>
              </figure>
            <% end %>
            <%= button_to root_path, class: "relative inline-flex items-center justify-center p-8 px-10 py-4 overflow-hidden font-medium text-white transition duration-300 ease-out border-2 border-white rounded-full shadow-md group", method: :get do %>
              <span class="absolute inset-0 flex items-center justify-center w-full h-full text-orange-400 duration-300 -translate-x-full bg-white group-hover:translate-x-0 ease">
                <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M14 5l7 7m0 0l-7 7m7-7H3"></path>
                </svg>
              </span>
              <span class="absolute flex items-center justify-center w-full h-full text-white transition-all duration-300 transform group-hover:translate-x-full ease">
                Accueil
              </span>
            <% end %>
          </section>
          <div id="map" class="h-52 my-5 w-[100%]" data-latitude="<%= @report.latitude %>" data-longitude="<%= @report.longitude %>" data-address="<%= @report.address %>"></div>       
        </section>
      </div>
    </div>
  </article>
  <article class="md:flex md:justify-center mt-8 md:mx-4 mx-auto">
    <% if current_user && current_user.is_admin && @report.is_validate == nil %>
      <%= button_to "Valider le signalement", admin_report_path(@report), class:"cstm-bg-valid-dark cstm-light font-bold py-2 px-4 rounded-full mt-4 md:mr-5", method: :patch, params: { "report" =>  "true" } %>
      <%= button_to "Refuser le signalement", admin_report_path(@report), class:"cstm-bg-action cstm-light font-bold py-2 px-4 rounded-full mt-4 md:mr-5", method: :patch, params: { "report" => "false" } %>
    <% elsif current_user && current_user.is_admin && @report.status == "validé" %>
      <%= button_to "Travaux programmés", admin_report_path(@report), class:"cstm-bg-valid-dark cstm-light font-bold py-2 px-4 rounded-full mt-4 md:mr-5", method: :patch, params: { "report" =>  "accepted" } %>
      <%= button_to "Travaux en cours", admin_report_path(@report), class:"cstm-bg-valid-dark cstm-light font-bold py-2 px-4 rounded-full mt-4 md:mr-5", method: :patch, params: { "report" =>  "in progress" } %>
      <%= button_to "Travaux terminés", admin_report_path(@report), class:"cstm-bg-valid-dark cstm-light font-bold py-2 px-4 rounded-full mt-4 md:mr-5", method: :patch, params: { "report" =>  "resolved" } %>
    <% elsif current_user && current_user.is_admin && @report.status == "accepté" %>
      <%= button_to "Travaux en cours", admin_report_path(@report), class:"cstm-bg-valid-dark cstm-light font-bold py-2 px-4 rounded-full mt-4 md:mr-5", method: :patch, params: { "report" =>  "in progress" } %>
      <%= button_to "Travaux terminés", admin_report_path(@report), class:"cstm-bg-valid-dark cstm-light font-bold py-2 px-4 rounded-full mt-4 md:mr-5", method: :patch, params: { "report" =>  "resolved" } %>
    <% elsif current_user && current_user.is_admin && @report.status == "en cours" %>
      <%= button_to "Etape précédente", admin_report_path(@report), class:"cstm-bg-valid-dark cstm-light font-bold py-2 px-4 rounded-full mt-4 md:mr-5", method: :patch, params: { "report" =>  "accepted" } %>
      <%= button_to "Travaux terminés", admin_report_path(@report), class:"cstm-bg-valid-dark cstm-light font-bold py-2 px-4 rounded-full mt-4 md:mr-5", method: :patch, params: { "report" =>  "resolved" } %>
    <% elsif current_user && current_user.is_admin && @report.status == "résolu" %>
      <%= button_to "Etape précédente", admin_report_path(@report), class:"cstm-bg-valid-dark cstm-light font-bold py-2 px-4 rounded-full mt-4 md:mr-5", method: :patch, params: { "report" =>  "in progress" } %>
    <% end %>
    <% if current_user && current_user.is_admin %>
      <%= button_to "Supprimer", admin_report_path(@report), class:"cstm-bg-danger cstm-light font-bold py-2 px-4 rounded-full mt-4", method: :delete %>
    <% end %>
  </article>
  <%= turbo_frame_tag "comments" do %>
    <article class="max-w-screen-xl w-full grid grid-cols-1 p-4 mb-4">
      <div id="comments-section">
        <%= render partial: 'comments/comments', locals: { report: @report } %>
      </div>
      <% if current_user %>
        <%= render partial: 'comments/form', locals: { report: @report } %>
      <% else %>
      <div class="mx-auto grid grid-cols-1 pt-6">
        <p class="font-semibold text-lg cstm-dark text-center">
          Déja sur notre site ?
          <%= link_to "Connecte-toi.", new_user_session_path, class: "font-medium cstm-primary hover:underline" %>
        </p>
        <p class="font-semibold text-lg cstm-dark text-center">
          Pas encore de compte ?
          <%= link_to "Je m'inscris.", new_user_registration_path, class: "font-medium cstm-primary hover:underline" %>
        </p>
      </div>
      <% end %>
    </article>
  <% end %>
</div>
<%= javascript_import_module_tag 'map_controller' %>

app/views/reports/edit.html.erb
<article class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing report</h1>
  <%= render "form", report: @report %>
  <%= link_to "Show this report", @report, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to reports", reports_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</article>

app/views/reports/index.html.erb
<article class="grid grid-cols-1 gap-6">
  <h2 class="text-3xl text-center font-semibold cstm-dark">
    Les signalements en cours
  </h2>
  <div class="text-center">
    <%= link_to 'Cliquez-ici pour voir les signalements sur la carte', map_path, class: "hover:text-orange-500 transition-colors duration-200 cstm-dark font-semibold text-xl", data: { turbo: "false" }  %>
  </div>
  <% @reports.sort.reverse_each do |report| %>
    <%= render report %>
  <% end %>
</article>

app/views/reports/new.html.erb
<article class="w-full lg:w-7/12 p-5 cstm-bg-sand shadow-2xl justify-items-center">
  <%= render "form", report: @report %>
</article>
<%= javascript_import_module_tag 'api_controller' %>

app/views/reports/show.html.erb
<%= render 'show' %>