config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :contact_mailer, only: [:new, :create] do
    collection do
      get :confirmation
    end
  end

  get '/conditions' => 'static_pages#conditions'
  get '/home' => 'static_pages#home'
  get '/map' => 'static_pages#map'

  resources :reports, except: [:edit] do
    resources :comments, only: [:create, :update, :destroy]
    resources :report_likes, only: [:create, :destroy]
  end

  resources :replies

  resources :users, only: [:show, :edit, :update, :destroy]

  root to: "static_pages#home"

  namespace :admin do
    root to: 'admin#index'
    resources :users, :reports
  end
end

app/views/layouts/_alerts.html.erb
<section id="show_notice" <%="data=#{notice.present?}" if notice.present?%> class="<%= 'hidden' unless notice.present? %>">
  <div class="justify-center text-center">
    <div class="bg-teal-100 border-t-4 border-teal-500 rounded-b text-teal-900 px-4 py-4 pl-7 shadow-md">
      <div class="py-1 flex items-center justify-center">
        <svg class="fill-current h-6 w-6 text-teal-500 mr-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
          <path d="M2.93 17.07A10 10 0 1 1 17.07 2.93 10 10 0 0 1 2.93 17.07zm12.73-1.41A8 8 0 1 0 4.34 4.34a8 8 0 0 0 11.32 11.32zM9 11V9h2v6H9v-4zm0-6h2v2H9V5z"/>
        </svg>
      </div>
      <div>
        <p class="font-bold">
          Information
        </p>
        <p class="text-sm">
          <%= notice %>
        </p>
      </div>
    </div>
  </div>
</section>
<section id="show_alert" <%="data=#{alert.present?}" if alert.present?%> class="<%= 'hidden' unless alert.present? %>">
  <div class="justify-center text-center">
    <div role="alert">
      <div class="bg-red-500 text-white font-bold rounded-t px-4 py-2">
        Attention
      </div>
      <div class="border border-t-0 border-red-400 rounded-b bg-red-100 px-4 py-3 text-red-700">
        <p>
          <%= alert %>
        </p>
      </div>
    </div>
  </div>
</section>

app/views/layouts/_banner.html.erb
<%= link_to root_path do %>
  <%= image_tag("banner.svg", class: "w-full", draggable: "false", alt: "Photo de la bannière") %>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <hr class="h-1 w-full cstm-bg-yellow">
  <hr class="h-1 w-full cstm-bg-primary">
  <hr class="h-1 w-full cstm-bg-light">
  <hr class="h-1 w-full cstm-bg-dark">
  <article class="relativ pt-2.5">
    <section class="page-section flex justify-center items-center" id="footer">
      <div class="container text-center">
        <div class="flex justify-center">
          <div class="col-start-3 col-end-4">
            <img src="<%= asset_path('bouxwiller_logo.svg') %>" class="mx-auto h-[60px] w-[60px]" alt="bouxwiller_logo">
            <h4 class="text-center">Ville de Bouxwiller</h4>
            <a class="btn btn-dark btn-social mx-2" href="https://www.facebook.com/mairiedebouxwiller67/" target=_blank aria-label="Facebook de votre commune"><i class="fab fa-facebook-f"></i></a>
            <a class="btn btn-dark btn-social mx-2" href="https://bouxwiller.eu/" target=_blank aria-label="Site de votre commune"><i class="far fa-building"></i></a>
          </div>  
        </div>
      </div>
    </section>
    <section class="md:whitespace-nowrap md:justify-between mx-auto">
      <div class="w-full px-4 mx-auto text-center">
        <div class="text-md cstm-dark font-semibold py-1">
          <%= link_to "Ma Voirie |", root_path, class: "cstm-dark hover:text-orange-800 whitespace-nowrap	" %>
          <%= link_to "Conditions générales d'utilisation |", '/conditions' ,class: "cstm-dark hover:text-orange-800 whitespace-nowrap	"%>
          <%= link_to 'Contact', new_contact_mailer_path, data: { turbo: false}, class: 'cstm-dark hover:text-orange-800' %>
        </div>
      </div>  
    </section>
  </article>
</footer>

app/views/layouts/_navbar.html.erb
<nav class="cstm-dark w-full">
  <button data-collapse-toggle="navbar-default" type="button" class="inline-flex items-center p-2 ml-3 text-sm rounded-lg md:hidden" aria-controls="navbar-default" aria-expanded="false">
    <span class="sr-only">Open main menu</span>
    <svg class="w-6 h-6" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
    <path fill-rule="evenodd" d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 15a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z" clip-rule="evenodd"></path></svg>
  </button>
  <article class="hidden md:block md:w-auto justify-start" id="navbar-default">
    <div class="md:flex">
      <ul class="w-full font-medium flex flex-col p-4 md:p-0 mt-4  rounded-lg md:flex-row md:mt-0">
        <li class="md:px-1 md:py-2 md:ml-[4%] xl:ml-[13%]">
          <%= link_to "Accueil", root_path, class:"nav-btn text-2xl font-semibold whitespace-nowrap drop-shadow-xl" %>
        </li>
        <li class="md:px-1 md:py-2 md:ml-[1%] lg:ml-[2%]">
          <%= link_to "Signalements", reports_path, class:"nav-btn text-2xl font-semibold whitespace-nowrap drop-shadow-xl" %>
        </li>
        <% if current_user %>
          <li class="md:px-1 md:py-2 md:ml-[1%] lg:ml-[2%]">
            <%= link_to "Nouveau signalement", new_report_path, class:"nav-btn text-2xl font-semibold whitespace-nowrap drop-shadow-xl", data:{turbo: false} %>
          </li>
        <% else %>
          <li class="md:px-1 md:py-2 md:ml-[1%] lg:ml-[2%]">
            <%= link_to "Nouveau signalement", new_user_session_path, class:"nav-btn text-2xl font-semibold whitespace-nowrap drop-shadow-xl" %>
          </li>
        <% end %>
      </ul>
      <div class="flex items-center md:ml-auto md:mr-[6%] lg:mr-[15%] ml-4" id="to_right">
        <% if current_user %>
        <div class="nav-btn">
          <button id="dropdownNavbarLink" data-dropdown-toggle="dropdownNavbar" class="flex items-center text-2xl font-semibold whitespace-nowrap">
            <span class="nav-btn text-2xl font-semibold whitespace-nowrap drop-shadow-xl mr-2">
              <%= current_user.nickname %>
            </span>
            <%= image_tag("user.svg", class: "w-10 md:mt-1 drop-shadow", draggable: "false", alt: "Icone utilisateur") %>
          </button>
        </div>
        <% else %>
          <button id="dropdownNavbarLink" data-dropdown-toggle="dropdownNavbar" class="flex items-center text-2xl font-semibold whitespace-nowrap">
            <span class="nav-btn text-2xl font-semibold whitespace-nowrap drop-shadow-xl mr-2">
              Se connecter
            </span>
            <%= image_tag("user.svg", class: "w-10 md:mt-1", draggable: "false", alt: "Icone utilisateur") %>
          </button>
        <% end %>
        <div id="dropdownNavbar" class="z-10 hidden font-normal bg-white divide-y divide-gray-100 rounded-lg shadow w-44">
          <% if current_user %>
            <ul>
              <% if current_user.is_admin %>
                <li>
                  <%= link_to "Dashboard admin", admin_root_path, class:"w-full text-center block px-4 py-2 hover:bg-gray-100" %>
                </li>
              <% end %>
              <li>
                <%= link_to "Mon profil", user_path(current_user), class:"w-full text-center block px-4 py-2 hover:bg-gray-100" %>
              </li>
              <li>
                <%= button_to "Me déconnecter", destroy_user_session_path, class:"w-full text-center block px-4 py-2 hover:bg-gray-100",form: { data: { turbo_confirm: "Veux-tu te déconnecter ?" } }, method: :delete %>
              </li>
            </ul>
          <% else %>
            <div class="py-1">
                <%= link_to "Connexion", new_user_session_path, class:"w-full text-center block px-4 py-2 hover:bg-gray-100" %>
            </div>
            <ul class="py-2 text-sm cstm-dark">
              <li>
                <p class="text-center">
                  Vous n'avez pas encore de compte ?
                  <%= link_to "Cliquez ici pour vous enregistrer.", new_user_registration_path, class:"block px-4 py-2 hover:bg-gray-100 cstm-primary" %>
                </p>
              </li>
            </ul>
          <% end %>
        </div>
      </div>
    </div>
  </article>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="fr">
  <head>
    <title>MaVoirie</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="description" content="Ma Voirie est un site en ligne qui offre aux utilisateurs la possibilité de signaler facilement les problèmes de voirie qu'ils rencontrent dans leur commune. Le site vise à faciliter la communication entre les citoyens et les autorités locales responsables de l'entretien des routes, des trottoirs et des espaces publics.">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="icon" type="image/x-icon" href="/favicon/favicon.svg" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css" integrity="sha384-DyZ88mC6Up2uqS4h/KRgHuoeGwBcD4Ng9SiP4dIRy0EXTlnuz47vAwmeGwVChigm" crossorigin="anonymous"/>
    <link rel="canonical" href="https://ma-voirie.herokuapp.com"/>
    <link href="https://fonts.googleapis.com/css2?family=Yatra+One&display=swap" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.6.5/flowbite.min.css" rel="stylesheet" />
    <link href="https://unpkg.com/dropzone@6.0.0-beta.1/dist/dropzone.css" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.11.4/css/lightbox.css" integrity="sha512-Woz+DqWYJ51bpVk5Fv0yES/edIMXjj3Ynda+KWTIkGoynAMHrqTcDUQltbipuiaD5ymEo9520lyoVOo9jCQOCA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link rel="stylesheet" href="https://unpkg.com/leaflet/dist/leaflet.css" /> 
  </head>
  <body id="top">
    <header>
      <%= render 'layouts/banner' %>
      <%= render 'layouts/navbar' %>
      <%= render 'layouts/alerts' %>
    </header>
    <main class="container mx-auto mt-8 px-1 pb-10 flex justify-center items-center">
      <%= javascript_importmap_tags %>
      <%= yield %>
    </main>
    <%= render 'layouts/footer'%>
    <script src="https://unpkg.com/leaflet/dist/leaflet.js"></script>
    <script src="https://www.google.com/recaptcha/api.js?render=explicit" async defer></script>
    <script src="https://kit.fontawesome.com/fc19c0866a.js" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://unpkg.com/flowbite@1.5.1/dist/flowbite.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.6.5/flowbite.min.js"></script>
    <script src='https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.7.3/dist/alpine.min.js'></script>
    <script src="https://cdn.tailwindcss.com"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.11.4/js/lightbox.min.js" integrity="sha512-Ixzuzfxv1EqafeQlTCufWfaC6ful6WFqIz4G+dWvK0beHw0NVJwvCKSgafpy5gwNqKmgUfIBraVwkKI+Cz0SEQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
  </body>
</html>